# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3568872b2b1a5ff610c1405d6b565bdf"
name = "qr-app"
handle = "qr-app-116"
application_url = "https://stating-investing-consisting-plugins.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dawn-customized-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://stating-investing-consisting-plugins.trycloudflare.com/auth/callback",
  "https://stating-investing-consisting-plugins.trycloudflare.com/auth/shopify/callback",
  "https://stating-investing-consisting-plugins.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
